"""Add organization, course_url, modules_count to Course model

Revision ID: 327e88d0b915
Revises: 9e536c298807
Create Date: 2025-09-16 05:15:49.531047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327e88d0b915'
down_revision = '9e536c298807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
