"""add_like_unlike_unenroll_columns_to_user_learning_profile

Revision ID: 52379b2d0d59
Revises: 7200b647383f
Create Date: 2025-09-20 19:21:54.005194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52379b2d0d59'
down_revision = '7200b647383f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to analytics.user_learning_profile table
    op.execute("""
        ALTER TABLE analytics.user_learning_profile 
        ADD COLUMN IF NOT EXISTS total_courses_liked INTEGER DEFAULT 0
    """)
    
    op.execute("""
        ALTER TABLE analytics.user_learning_profile 
        ADD COLUMN IF NOT EXISTS total_courses_unliked INTEGER DEFAULT 0
    """)
    
    op.execute("""
        ALTER TABLE analytics.user_learning_profile 
        ADD COLUMN IF NOT EXISTS total_courses_unenrolled INTEGER DEFAULT 0
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the added columns
    op.execute("""
        ALTER TABLE analytics.user_learning_profile 
        DROP COLUMN IF EXISTS total_courses_liked
    """)
    
    op.execute("""
        ALTER TABLE analytics.user_learning_profile 
        DROP COLUMN IF EXISTS total_courses_unliked
    """)
    
    op.execute("""
        ALTER TABLE analytics.user_learning_profile 
        DROP COLUMN IF EXISTS total_courses_unenrolled
    """)
    # ### end Alembic commands ###
