"""add_enrollments_table

Revision ID: 618796f25021
Revises: a488eb2fe043
Create Date: 2025-09-18 03:00:17.532281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618796f25021'
down_revision = 'a488eb2fe043'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enrollments_completion', 'enrollments', ['is_completed', 'completion_date'], unique=False)
    op.create_index('ix_enrollments_course_enrollment_date', 'enrollments', ['course_id', 'enrollment_date'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index('ix_enrollments_user_course', 'enrollments', ['user_id', 'course_id'], unique=True)
    op.create_index('ix_enrollments_user_enrollment_date', 'enrollments', ['user_id', 'enrollment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrollments_user_enrollment_date', table_name='enrollments')
    op.drop_index('ix_enrollments_user_course', table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index('ix_enrollments_course_enrollment_date', table_name='enrollments')
    op.drop_index('ix_enrollments_completion', table_name='enrollments')
    op.drop_table('enrollments')
    # ### end Alembic commands ###
