"""add_user_interactions_user_preferences_recommendation_tables

Revision ID: 7200b647383f
Revises: 8912c09c665e
Create Date: 2025-09-20 16:52:05.315762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7200b647383f'
down_revision = '8912c09c665e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
