"""add_deleted_date_in_enrollmentsRename deleted_date to deleted_at in enrollments table ||  goto :error

Revision ID: 8912c09c665e
Revises: e790e6d6a67b
Create Date: 2025-09-19 08:15:48.195422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8912c09c665e'
down_revision = 'e790e6d6a67b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('enrollments', 'deleted_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('deleted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('enrollments', 'deleted_at')
    # ### end Alembic commands ###
