"""Add organization, course_url, modules_count to Course model

Revision ID: 9e536c298807
Revises: c6180f64edca
Create Date: 2025-09-16 05:10:54.899883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e536c298807'
down_revision = 'c6180f64edca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('organization', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('course_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('modules_count', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'modules_count')
    op.drop_column('courses', 'course_url')
    op.drop_column('courses', 'organization')
    # ### end Alembic commands ###
