"""add_skills_field_to_courses

Revision ID: a488eb2fe043
Revises: 327e88d0b915
Create Date: 2025-09-17 04:33:44.043451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a488eb2fe043'
down_revision = '327e88d0b915'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('skills', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'skills')
    # ### end Alembic commands ###
