"""add_deleted_date_in_enrollments

Revision ID: e790e6d6a67b
Revises: 618796f25021
Create Date: 2025-09-18 04:59:44.079702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e790e6d6a67b'
down_revision = '618796f25021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('deleted_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'deleted_date')
    # ### end Alembic commands ###
